//
// Created by yo on 2/22/19.
//

#ifndef ANITAGS_ERROR_CODES_HPP
#define ANITAGS_ERROR_CODES_HPP

#define SUCCESS                     0
#define ERROR_OPTION_S_WITH_T_R     1
#define ERROR_FILE_REQUIRED         2
#define ERROR_FILE_DOES_NOT_EXIST   3
#define ERROR_EXECUTING_EXIFTOOL    4
#define ERROR_INVALID_ARGUMENT      5
#define ERROR_ARGUMENT_IS_DIRECTORY 6

#endif //ANITAGS_ERROR_CODES_HPP
